### ISSUE TITLE
Update API Domain 

### ISSUE THREAD

**Issue by RWavicado** [singer-io/tap-toggl#7]
Toggl is changing their API domain name on June 30th because of a company rebrand. The new domain is api.track.toggl.com. Can this be updated to keep a smooth flow of data? Here is more information about the change, including a link to documentation: 
https://toggl.com/blog/api-documentation-change

**Comment by Leerstelle** [comment]
+1

**Comment by chase2963** [comment]
Yep seeing the same issue here, just got an email about this today: https://a.cl.ly/JruD10EB

**Comment by luandy64** [comment]
This was updated thanks to @chrisgre in #8 

I deployed it in `v1.0.3`, so I'm closing this issue
